### ISSUE TITLE
build kernel for arm systems

### ISSUE THREAD

**Issue by jdonszelmann** [baas-project/baas#3]
Currently, the kernel build process only works for x86 machines. Since we also target arm machines this needs to change. Cross compiling is a pain so it will probably end up being a set of scripts we have to run on an arm machine to compile Linux. But these have to be created.

**Comment by ValentijnvdBeek** [comment]
Kernel building has been obsoleted (hopefully) after merging #25, hence this issue is closed since it is no longer relevant
